Update Dockerfile

diff --git a/view/Dockerfile b/view/Dockerfile
--- a/view/Dockerfile
+++ b/view/Dockerfile
@@ -1,19 +1,54 @@
-# Dockerfile for hnz-view service
-
-# Base image
-FROM node:latest
-
-# Set the working directory
-WORKDIR /view
-
-# Copy the rest of the application
-COPY ./ /view
+FROM node:18-alpine AS base
 
 # Install dependencies
-RUN yarn install
+FROM base AS deps
 
-# Expose the port
-EXPOSE 3030
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-# Default command to run the application
-CMD ["sh", "-c", "PORT=3030 yarn dev"]
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Rebuild source code 
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+ENV NEXT_TELEMENTRY_DISABLED 1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+
+ENV NEXT_TELEMENTRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+
+CMD HOSTNAME="0.0.0.0" node server.js
